config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :tombos,:only => [:index], :collection => {:usuario => :get, :livros_diarios => :get,:de_diarios => :get}
  map.resources :logs
  map.resources :consultas,:only => [:index] , :collection => {:global => :get,:gerar_tombos => :get,:criar_consulta => :get, :lista_tombo => :get}
  map.resources :midias, :collection => {:midias_cadastradas => :get}

  map.resources :musicas
  map.resources :cantores
  map.resources :generos
  map.resources :roles_users, :collection => {:lista_users => :get}
  map.resources :configuracoes
  map.resources :importar
  map.resources :emprestimos, :member => [:devolucao],:collection => {:ativos => :get,:realiza_busca => :get,:busca_emprestimo => :get,:funcionario => :get, :alunos => :get,:classe => :get, :dpu => :get, :busca => :get, :devolve_unit => :get}
  map.resources :funcionarios
  map.resources :tipos
  map.resources :unidades
  map.resources :musicas
  map.resources :autores
  map.resources :itens_assuntos
  map.resources :assuntos
  map.resources :jogos, :collection => {:jogos_cadastrados => :get}
  map.resources :periodicos
  map.resources :mapas
  map.resources :mapas
  map.resources :dicionario_enciclopedias, :collection => {:de_cadastrados => :get}
  map.resources :livros,:collection => {:livros_cadastrados => :get}

  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'

  map.resources :users
  map.resource :session

  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.resource :password
  map.reset_password '/reset_password/:id', :controller => 'passwords', :action => 'edit'
  map.resources :users
  map.resumo '/resumo/:livro', :controller => 'livros', :action => 'resumo'

  map.consultaDic '/consultaDic', :controller => 'dicionario_enciclopedias', :action => 'consultaDic'
  map.consultaLiv '/consultaLiv', :controller => 'livros', :action => 'consultaLiv'
  map.consultaJog '/consultaJog', :controller => 'jogos', :action => 'consultaJog'
  map.consultaMap '/consultaMap', :controller => 'mapas', :action => 'consultaMap'
  map.consultaAut '/consultaAut', :controller => 'autores', :action => 'consultaAut'
  map.consultaAutLiv '/consultaAutLiv', :controller => 'autores', :action => 'consultaAutLiv'
  map.consultaAre '/consultaAre', :controller => 'areas', :action => 'consultaAre'
  map.consultaAreLiv '/consultaAreLiv', :controller => 'areas', :action => 'consultaAreLiv'
  map.consultaEdi '/consultaEdi', :controller => 'editoras', :action => 'consultaEdi'
  map.consultaEdiLiv '/consultaEdiLiv', :controller => 'editoras', :action => 'consultaEdiLiv'
  map.consultaTit '/consultaTit', :controller => 'identificacaos', :action => 'consultaTit'
  map.consultaGen '/consultaGen', :controller => 'generos', :action => 'consultaGen'
  map.consultaCan '/consultaCan', :controller => 'cantores', :action => 'consultaCan'
  map.consultaCanMus '/consultaCanMus', :controller => 'cantores', :action => 'consultaCanMus'
  map.consultaMus '/consultaMus', :controller => 'musicas', :action => 'consultaMus'
  map.consultaAud '/consultaAud', :controller => 'audio_visuais', :action => 'consultaAud'
  map.consultaMid '/consultaMid', :controller => 'midias', :action => 'consultaMid'
  map.consultaAsu '/consultaAsu', :controller => 'assuntos', :action => 'consultaAsu'
  map.consultaAsuLiv '/consultaAsuLiv', :controller => 'assuntos', :action => 'consultaAsuLiv'
  

  map.resource :session
  map.resources :editoras
  map.resources :areas
  map.resources :localizacoes
  map.resources :identificacaos

  map.home '', :controller => 'home', :action => 'index'
  map.root :controller => "home"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/midia.rb
class Midia < ActiveRecord::Base
  has_many :possuis, :dependent => :destroy
  has_many :dpus, :dependent => :destroy
  belongs_to :genero
  belongs_to :localizacao
  has_many :tombos, :dependent => :destroy
  after_create :multi_tombo, :cria_possui_md, :auto_inc_tombo_seduc, :cria_disponibiliza_md
  attr_accessor :qtde_midias, :lista_tombos, :usuario, :unidade

  has_and_belongs_to_many :musicas
  has_and_belongs_to_many :cantores
  validates_presence_of :lista_tombos, :if => :qtde?
  validates_presence_of :genero_id
  validates_presence_of :localizacao_id
  validates_presence_of :titulo
  validates_presence_of :tipo
  validates_presence_of :subtitulo
  TIPO = %w(CD DVD VHS OUTRAS)


  def qtde?
    self.qtde_midias == 1
  end
  def multi_tombo
    multi = Tombo.new
    multi.midia_id = self.id
    multi.user_id = self.usuario
    multi.index_tombo = "#{self.id} - #{self.usuario}"
    multi.qtde_livro = self.qtde_midias
    multi.save
  end
  def auto_inc_tombo_seduc
    self.tombo_seduc = self.id
  end
  def cria_possui_md
    possui = Possui.new
    possui.unidade_id = self.unidade
    possui.tombo = "md-#{self.tombo_l}"
    #possui.midia_id = self.id
    possui.status = 1
    possui.save
  end

  def cria_disponibiliza_md
    disp = Dpu.new
    disp.unidade_id = self.unidade
    disp.tombo = "md-#{self.tombo_l}"
    #disp.midia_id = self.id
    disp.status = 1
    disp.save
  end


end

app/views/shared/campos/_assunto.html.erb
<%= select_tag("todos", options_for_select(@assuntos.collect { |ff| [ff.descricao, ff.id] }, @livro.assuntos.collect { |fs| fs.id }), {:multiple=>true, :id => "todos", :size => 4, :class => "lista_assuntos"}) %>

app/views/shared/campos/_campos_assunto.html.erb
  <tr>
    <td id="test"><%= select_tag("todos", options_for_select(@assuntos.collect { |ff| [ff.descricao, ff.id] }, @livro.assuntos.collect { |fs| fs.id }), {:multiple=>true, :id => "todos", :size => 4, :class => "lista_assuntos"}) %></td>
    <%if @assuntos_selecionados.present?%>
      <td><%= select_tag("livro[assunto_ids][]", options_for_select(@assuntos_selecionados.collect { |ff| [truncate(ff.descricao, :length => 30, :omission => "..."), ff.id] }, @livro.assuntos.collect { |fs| fs.id }), {:multiple=>true, :id => "livro_assunto_ids", :size => 4, :class => "lista_assuntos"}) %></td>
    <%else%>
      <td><select multiple="multiple" name="livro[assunto_ids][]" id="livro_assunto_ids" class="lista_assuntos"></select></td>
    <%end%>
  </tr>
  <tr>
    <td><a class="botao" href="#" id="add">&gt;&gt;</a></td>
    <td><a class="botao" href="#" id="remove">&lt;&lt;</a></td>
  </tr>

app/views/shared/campos/_campos_autor.html.erb
<div class="fields">
  <tr>
    <td><%= select_tag("todos_autores", options_for_select(@autores.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @livro.autores.collect { |fs| fs.id }), {:multiple=>true, :id => "todos_autores", :size => 5, :class => "lista_autores"}) %></td>
    <%if @autores_selecionados.present?%>
      <td><%= select_tag("livro[autor_ids][]", options_for_select(@autores_selecionados.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @livro.autores.collect { |fs| fs.id }), {:multiple=>true, :id => "livro_autor_ids", :size => 5, :class => "lista_autores"}) %></td>
    <%else%>
      <td ><select multiple="multiple" name="livro[autor_ids][]" id="livro_autor_ids" class="lista_autores"></select></td>
    <%end%>
  </tr>
  <tr>
    <td><a class="botao" href="#" id="add_autores">&gt;&gt;</a></td>
    <td><a class="botao" href="#" id="remove_autores">&lt;&lt;</a></td>
  </tr>
</div>

app/views/shared/campos/_campos_cantor.html.erb
<div class="fields">
  <tr class="musica">
    <td id="cantores"><%= select_tag("todos_cantores", options_for_select(@cantores.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @midia.cantores.collect { |fs| fs.id }), {:multiple=>true, :id => "todos_cantores", :size => 5, :class => "lista_cantores"}) %></td>
    <%if @cantores_selecionados.present?%>
      <td><%= select_tag("midia[cantor_ids][]", options_for_select(@cantores_selecionados.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @midia.cantores.collect { |fs| fs.id }), {:multiple=>true, :id => "midia_cantor_ids", :size => 5, :class => "lista_cantores"}) %></td>
    <%else%>
      <td><select multiple="multiple" name="midia[cantor_ids][]" id="midia_cantor_ids" class="lista_cantores"></select></td>
    <%end%>
  </tr>
  <tr class="musica">
    <td><a class="botao" href="#" id="add_cantores">&gt;&gt;</a></td>
    <td><a class="botao" href="#" id="remove_cantores">&lt;&lt;</a></td>
  </tr>
</div>

app/views/shared/campos/_campos_editora.html.erb
        
        <%= collection_select :livro,:editora_id ,@editoras,:id,:nome, :include_blank => "--Selecionar--" %>

app/views/shared/campos/_campos_emprestimos.html.erb
<div class="fields">
  <tr>
    <td><%= select_tag("todos_livros", options_for_select(@autores.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @livro.autores.collect { |fs| fs.id }), {:multiple=>true, :id => "todos_livros", :size => 5, :class => "lista_autores"}) %></td>
    <%if @autores_selecionados.present?%>
      <td><%= select_tag("livro[autor_ids][]", options_for_select(@autores_selecionados.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @livro.autores.collect { |fs| fs.id }), {:multiple=>true, :id => "livro_autor_ids", :size => 5, :class => "lista_autores"}) %></td>
    <%else%>
      <td><select multiple="multiple" name="livro[autor_ids][]" id="livro_autor_ids" class="lista_autores"></select></td>
    <%end%>
  </tr>
  <tr>
    <td><a class="botao" href="#" id="add_autores">&gt;&gt;</a></td>
    <td><a class="botao" href="#" id="remove_autores">&lt;&lt;</a></td>
  </tr>
</div>

app/views/shared/campos/_campos_identificacao.html.erb
<%= collection_select :livro,:identificacao_id ,@identificacoes,:id,:truncated_value, :include_blank => "--Selecionar--" %>

app/views/shared/campos/_campos_local.html.erb
<% if current_user.unidade_id == 53 %>
  <%= collection_select define_model(encontra_model(request.request_uri ).to_s.singularize), :localizacao_id ,@localizacoes,:id,:concat_locale, :include_blank => "--Selecionar--" %>
<%else%>
  <%= collection_select define_model(encontra_model(request.request_uri ).to_s.singularize), :localizacao_id ,@localizacoes,:id,:local_guardado, :include_blank => "--Selecionar--" %>
<%end%>

app/views/shared/campos/_campos_musica.html.erb
<div class="fields">
  <tr class="musica">
    <td id="lista_musicas"><%= select_tag("todas_musicas", options_for_select(@musicas.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @midia.musicas.collect { |fs| fs.id }), {:multiple=>true, :id => "todas_musicas", :size => 5, :class => "lista_musicas"}) %></td>
    <%if @musicas_selecionadas.present?%>
      <td><%= select_tag("midia[musica_ids][]", options_for_select(@musicas_selecionadas.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @midia.musicas.collect { |fs| fs.id }), {:multiple=>true, :id => "midia_musica_ids", :size => 5, :class => "lista_musicas"}) %></td>
    <%else%>
      <td><select multiple="multiple" name="midia[musica_ids][]" id="midia_musica_ids" class="lista_musicas"></select></td>
    <%end%>
  </tr>
  <tr class="musica">
    <td><a class="botao" href="#" id="add_musicas">&gt;&gt;</a></td>
    <td><a class="botao" href="#" id="remove_musicas">&lt;&lt;</a></td>
  </tr>
</div>

app/views/shared/campos/_cantor.html.erb
<%= select_tag("todos_cantores", options_for_select(@cantores.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @midia.cantores.collect { |fs| fs.id }), {:multiple=>true, :id => "todos_cantores", :size => 5, :class => "lista_cantores"}) %>

app/views/shared/campos/_musica.html.erb
<%= select_tag("todas_musicas", options_for_select(@musicas.collect { |ff| [truncate(ff.nome, :length => 30, :omission => "..."), ff.id] }, @midia.musicas.collect { |fs| fs.id }), {:multiple=>true, :id => "todas_musicas", :size => 5, :class => "lista_musicas"}) %>